In [1]:
"""Converts MNIST data to TFRecords file format with Example protos."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import os
import sys
## generating the training batches
import numpy as np
import scipy.io
from array import array
import pandas as pd
from PIL import Image

import tensorflow as tf

from matplotlib.pyplot import imshow
%matplotlib inline

In [2]:
def data_list(data_dir, label_dir, num_examples):
    '''
    imports: pandas, os, numpy, PIL
    '''
    width = 256
    height = 256
    #get labels csv into pandas df
    #below line assumes 
    label_file_name = os.listdir(label_dir)[0]
    label_pd = pd.read_csv(label_dir + label_file_name)
    #initilize container list
    data = [[],[]]
    #get filenames om images
    filenames = os.listdir(data_dir)
    #below loop retrieved the 
    for im_number in range(28500,num_examples-3500):
        #im = Image.open(data_dir + filenames[im_number]).resize((width, height), Image.ANTIALIAS)
        #im = np.asarray(im).reshape(1,width, height, 3)
        name = filenames[im_number].replace(".jpeg", "")
        label = label_pd.loc[label_pd['image'] == name].iloc[0]['level']
        data[0].append(name)
        #data[1].append(im)
        data[1].append(label)
        
    return(data)

In [3]:
label_dir = '/home/olle/PycharmProjects/Diabetic_Retinopathy_Detection/data/labels/'
data_dir = '/home/olle/PycharmProjects/Diabetic_Retinopathy_Detection/data/orig_images/train/'


In [4]:
filenames = os.listdir(data_dir)
len(filenames)

35126

In [5]:
filenames = os.listdir(data_dir)
num_examples = int(len(filenames))
data = data_list(data_dir, label_dir, num_examples)

class data_set(object):
    pass

#train_images = np.vstack(data[1])
train_labels = np.asarray(data[1])

    #train_images = train_images.transpose()
    #train_images = np.swapaxes(train_images, 1, 3)

#data_set.images = train_images
data_set.labels = train_labels
data_set.names = data[0]
data_set.num_examples = data_set.labels.shape[0]

#print(data[2])
#print(data_set.labels)
#print(data_set.images.shape)
#print("data_batch_{}.bin".format(i))
    
print(data_set.num_examples)

3126


In [6]:
train_class_dist = np.unique(data_set.labels,  return_counts=True)

In [11]:
test_class_dist = np.unique(data_set.labels,  return_counts=True)
test_class_dist[1]/data_set.num_examples

array([0.74504159, 0.06333973, 0.14107486, 0.02463212, 0.02591171])

In [8]:
validation_class_dist = np.unique(data_set.labels,  return_counts=True)
validation_class_dist

(array([0, 1, 2, 3, 4]), array([2329,  198,  441,   77,   81]))

In [9]:
#see so image is correct
print(data_set.labels[0])
imshow(data_set.images[0])

0


AttributeError: type object 'data_set' has no attribute 'images'

In [ ]:
type(np.asarray(data[2]))

In [20]:
dist = np.array([0.74504159, 0.06333973, 0.14107486, 0.02463212, 0.02591171])
factors = 1/dist
np.asarray(factors, dtype=np.int32)

array([ 1, 15,  7, 40, 38], dtype=int32)

In [25]:
    class_factors = np.array([ 1, 15,  7, 40, 38])
class_factors[1]

15

In [19]:
label_pd = pd.read_csv(label_dir + 'trainLabels.csv')
unique, counts = np.unique(label_pd['level'], return_counts = True)
props = counts/np.sum(counts)
factors = np.asarray(1/props, dtype = np.int32)
print([factors, counts,props])

[array([ 1, 14,  6, 40, 49], dtype=int32), array([25810,  2443,  5292,   873,   708]), array([0.73478335, 0.06954962, 0.15065763, 0.02485338, 0.02015601])]


In [39]:
l

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
data_dir = '/home/olle/PycharmProjects/Diabetic_Retinopathy_Detection/data/train/train/'
filenames = os.listdir(data_dir)
len(filenames)

In [ ]:
list = [2,3,4,5]
list

In [ ]:
np.asarray(list).reshape(4,1).shape

In [ ]:
list.append(np.array([4,3,5]))

In [ ]:
list