# Implementation below implements the weighted kappa metic for result benchmarking

In [23]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

In [62]:
arr1 = np.array([0,1,0,0,0,1,1,1,1,1])
arr2 = np.array([3,3,3,3,3,3,3,3,3,3])

In [63]:
np.unique(arr2)

array([3])

In [64]:
cm = confusion_matrix(y_true=arr1,y_pred=arr2)

In [ ]:
cm

In [75]:
import numpy as np

def quadratic_kappa(y, t, eps=1e-15):
    
    n_y_values = np.max(y) + 1
    n_t_values = np.max(t) + 1
    n = max(n_y_values, n_t_values)
    y_onehot = np.eye(n)[y]
    t_onehot = np.eye(n)[t]
    
    print(y_onehot)
    print(t_onehot)
    # Assuming y and t are one-hot encoded!
    num_scored_items = y_onehot.shape[0]
    
    num_ratings = y_onehot.shape[1] 
    ratings_mat = np.tile(np.arange(0, num_ratings)[:, None], 
                        reps=(1, num_ratings))
    ratings_squared = (ratings_mat - ratings_mat.T) ** 2
    weights = ratings_squared / (float(num_ratings) - 1) ** 2

    # We norm for consistency with other variations.
    y_norm = y_onehot / (eps + y_onehot.sum(axis=1)[:, None])

    # The histograms of the raters.
    hist_rater_a = y_norm.sum(axis=0)
    hist_rater_b = t_onehot.sum(axis=0)

    # The confusion matrix.
    conf_mat = np.dot(y_norm.T, t_onehot)
    print(weights.shape)
    print(conf_mat.shape)
    # The nominator.
    nom = np.sum(weights * conf_mat)
    expected_probs = np.dot(hist_rater_a[:, None], 
                          hist_rater_b[None, :])
    # The denominator.
    denom = np.sum(weights * expected_probs / num_scored_items)

    return 1 - nom / denom

In [76]:
quadratic_kappa(arr1, arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
(4, 4)
(4, 4)


0.0